const path = require('path')
const express = require('express')
const fileUploader = require('express-fileupload')
const auth = require('./routes/auth')
const users = require('./routes/users')
const profiles = require('./routes/profiles')
const imageUpload = require('./routes/imageUpload')
const photos = require('./routes/photos')

const app = express()
app.use(express.static(
   path.join(__dirname, 'public')
))
app.use(fileUploader())
app.use(express.json())
app.use('/api/auth', auth)
app.use('/api/users', users)
app.use('/api/profiles', profiles)
app.use('/api/upload', imageUpload)
app.use('/api/photos', photos)
app.listen(5000)
