const express = require('express')
const fileUploader = require('express-fileupload')
const auth = require('./routes/auth')
const users = require('./routes/users')
const imageUpload = require('./routes/imageUpload')

const app = express()
app.use(fileUploader({}))
app.use(express.json())
app.use('/auth', auth)
app.use('/users', users)
app.use('/upload', imageUpload)
app.listen(5000)
